wordをPDF変換してプレビュー表示する機能追加
beyonds-inc/vue-laravel-file-manager pull request #14
Opened 2024-07-05 05:47 UTC by chinachan

## プルリク概要

資料一覧から任意のdocx or docをクリック時に、ブラウザ上でそのwordファイルのプレビューを表示する

## 関連issue
■ ePortal
[#204](https://github.com/beyonds-inc/eportal-saas/issues/204)

2024-07-06 04:36 UTC, wertrew21 reviewed
@chinachan 
インデント、スペースについてコメントいたしました。
ご確認の程よろしくお願いします。

2024-07-06 04:36 UTC, wertrew21 commented on src/components/manager/mixins/manager.js
> +								var disk= this.selectedDisk;
インデントの調整お願いします！

2024-07-06 04:36 UTC, wertrew21 commented on src/components/manager/mixins/manager.js
> +				/**
こちらも他のPHPDocsのインデントを参考していただいて、ご調整の程よろしくお願いします。

2024-07-06 04:36 UTC, wertrew21 commented on src/components/manager/mixins/manager.js
> +								var disk= this.selectedDisk;
（スペース4つ）

2024-07-06 04:36 UTC, wertrew21 commented on src/components/manager/mixins/manager.js
> +								var disk= this.selectedDisk;
`var disk=` -> `var disk =`に修正の程お願いします。

2024-07-15 00:11 UTC, taka-beyonds requested changes
@chinachan 遅くなりましたがコメント入れました。

2024-07-15 00:11 UTC, taka-beyonds commented on src/components/manager/mixins/manager.js
> +								var disk = this.selectedDisk;
チェさんのコメントにもありますが、インデント調整お願いしますm()m

タブを半角スペース4個にしていただければ。
https://www.javadrive.jp/vscode/setting/index9.html

2024-07-15 00:11 UTC, taka-beyonds commented on src/components/manager/mixins/manager.js
> +												fileInfo = data;
206行目で、同じ`fileInfo`という変数を使っているので、変数名を変えてください。同じ変数名を別の使い方をしていると可読性が下がるので。

2024-07-15 00:11 UTC, taka-beyonds commented on src/components/manager/mixins/manager.js
> +												if (fileInfo.length==0){
`==`の前後と、`)`の後にスペースお願いします。

2024-07-15 00:11 UTC, taka-beyonds commented on src/components/manager/mixins/manager.js
> +        async sendFileToServer(disk, path) {
フロントエンドから、Wordファイルをサーバーに送る実装のままなんでしたっけ？
これは処理速度がすごく落ちそう（Wordファイルをダウンロード→アップロードの処理が必要となるため）なので
ファイルそのものはバックエンド側だけで処理してほしいです。

2024-07-23 02:08 UTC, chinachan commented on src/components/manager/mixins/manager.js
> +        async sendFileToServer(disk, path) {
@taka-beyonds 
slackの方でもご連絡しましたが、フロントエンドからからファイルの情報（diskとpath）をサーバーに送っているので、Wordファイルをサーバーに送る実装ではないという認識ですが、何か私の方で認識違いをしているようでしたらご指摘いただけますと幸いです。

2024-07-23 02:36 UTC, taka-beyonds commented on src/components/manager/mixins/manager.js
> +        async sendFileToServer(disk, path) {
@chinachan あ、いえ確認だけなので、僕の勘違いだったら大丈夫です！失礼しました。

2024-07-24 09:04 UTC, taka-beyonds approved these changes

2024-07-24 09:04 UTC, merged